### ISSUE TITLE
Null reference in Modal when run in react test renderer

### ISSUE THREAD

**Issue by kglickman** [IBM/carbon-components-react#1751]
## Detailed description
The component works fine in our real product, but when running tests using the 'react-test-renderer', we get this exception:

    TypeError: Cannot read property 'querySelector' of null

      at Modal.focusButton (node_modules/carbon-components-react/lib/components/Modal/Modal.js:141:55)
      at Modal.componentDidMount (node_modules/carbon-components-react/lib/components/Modal/Modal.js:180:12)

A simple null check will meet our needs.

> What browser are you working in?  
Chrome

> What version of the Carbon Design System are you using?
    "carbon-components": "^9.66.3",
    "carbon-components-react": "^6.74.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
OpenPages

**Comment by kglickman** [comment]
Just an FYI, this issue turned out to be because react-test-renderer doesn't support refs.  After this change, I still had a null pointer slightly later, when this.button.current.focus() was called.  The recommended way to deal with this problem is to mock a focus function.  https://reactjs.org/docs/test-renderer.html#ideas
